const versionNull = {
  version: null,
  userLevel: null,
  coins: null,
  hints: null,
  hintDarts: null,
  hintCompass: null,
  hasAdPass: null,
  eventPurchasedNewYear: null,
  levelIndex: null,
  skinIndex: null,
  partIndex: null,
  option_isPlayMusic: null,
  option_isPlaySFX: null,
  timer_StoreBtnReward: null,
  isTutorial_shadows: null,
  isTutorial_words: null,
  isTutorial_anagrams: null,
  isTutorial_generator: null,
  hintDartsIsAvailable: null,
  hintCompassIsAvailable: null,
  playerId: null,
  savedAt: null,
  currentSkin: null,
  skins: null,
}
const versionUndefined = {
  version: undefined,
  userLevel: undefined,
  coins: undefined,
  hints: undefined,
  hintDarts: undefined,
  hintCompass: undefined,
  hasAdPass: undefined,
  eventPurchasedNewYear: undefined,
  levelIndex: undefined,
  skinIndex: undefined,
  partIndex: undefined,
  option_isPlayMusic: undefined,
  option_isPlaySFX: undefined,
  timer_StoreBtnReward: undefined,
  isTutorial_shadows: undefined,
  isTutorial_words: undefined,
  isTutorial_anagrams: undefined,
  isTutorial_generator: undefined,
  hintDartsIsAvailable: undefined,
  hintCompassIsAvailable: undefined,
  playerId: undefined,
  savedAt: undefined,
  currentSkin: undefined,
  skins: undefined,
}

const freshVersion1 = {
  version: 0.0005,
  userLevel: 2025,
  hints: 777,
  hasAdPass: true,
  levelIndex: 66,
  skinIndex: 5,
  partIndex: 5,
  option_isPlayMusic: false,
  option_isPlaySFX: false,
  option_isLight: false,
  option_isDebug: false,
  timer_StoreBtnReward: null,
  timer_NoHintsPupUpBtnReward: null,
  isTutorial_generator: false,
  isTutorial_shadows: false,
  isTutorial_words: false,
  playerId: 'j+UJYGMJEgVdGO9clWRRnyOXY93+dEe9tgKORJdcG2Y=',
  savedAt: '2025-06-23T02:12:12.753Z'
}

const freshVersion2 = {
  version: 0.0005,
  userLevel: 2035,
  hints: 777,
  hasAdPass: true,
  levelIndex: 66,
  skinIndex: 5,
  partIndex: 5,
  option_isPlayMusic: false,
  option_isPlaySFX: false,
  option_isLight: false,
  option_isDebug: false,
  timer_StoreBtnReward: null,
  timer_NoHintsPupUpBtnReward: null,
  isTutorial_generator: false,
  isTutorial_shadows: false,
  isTutorial_words: false,
  playerId: 'j+UJYGMJEgVdGO9clWRRnyOXY93+dEe9tgKORJdcG2Y=',
  savedAt: '2035-06-23T02:12:12.753Z'
}

const stringVersion = {
  version: '0.0005',
  userLevel: '2026',
  hints: '555',
  hasAdPass: 'true',
  levelIndex: '66',
  skinIndex: '5',
  partIndex: '5',
  option_isPlayMusic: 'false',
  option_isPlaySFX: 'false',
  option_isLight: 'false',
  option_isDebug: 'false',
  timer_StoreBtnReward: 'null',
  timer_NoHintsPupUpBtnReward: 'null',
  isTutorial_generator: 'false',
  isTutorial_shadows: 'false',
  isTutorial_words: 'false',
  playerId: 'j+UJYGMJEgVdGO9clWRRnyOXY93+dEe9tgKORJdcG2Y=',
  savedAt: '2026-06-23T02:15:12.753Z'
}

export const TEST_DATA = {
  serverData: [
    null,
    {...versionUndefined},
  ],
  localData: [
    {...stringVersion},
    {...versionNull},
    {...freshVersion2},
  ],
}
