/**
 * Разрешение атласов, которое загружает игра.
 *
 * 1 — файлы без суффикса: atlas.webp
 * 2 — atlas@2x.webp
 * 3 — atlas@3x.webp
 */
const ATLAS_RESOLUTION = 2

// Разрешение canvas не может быть ниже качества выбранного атласа.
// devicePixelRatio передаётся снаружи, чтобы конфиг можно было импортировать в Node.js (AssetPack).
const getGameResolution = (devicePixelRatio = 1) => {
  return Math.max(ATLAS_RESOLUTION, devicePixelRatio)
}
/**
 * Варианты, создаваемые AssetPack.
 * Самое большое значение — плотность исходников в raw-assets.
 * Для 3x недостаточно просто поставить число 3: текущие исходники в raw-assets имеют плотность 2x.
 * Нужны реальные исходники 3x, после чего конфигурация должна выглядеть так:
 *
 * const ATLAS_RESOLUTION = 3
 *
 * const ATLAS_RESOLUTIONS = {
 *   default: 3,
 *   medium: 2,
 *   low: 1,
 * }
 */
const ATLAS_RESOLUTIONS = {
  default: 2,
  low: 1,
}

const availableResolutions = Object.values(ATLAS_RESOLUTIONS)

if (!availableResolutions.includes(ATLAS_RESOLUTION)) {
  throw new Error(
    `ATLAS_RESOLUTION=${ATLAS_RESOLUTION} is not generated by AssetPack. ` + `Available resolutions: ${availableResolutions.join(', ')}`,
  )
}

const getAtlasResolutionSuffix = (resolution = ATLAS_RESOLUTION) => {
  return resolution === 1 ? '' : `@${resolution}x`
}

export {ATLAS_RESOLUTION, ATLAS_RESOLUTIONS, getGameResolution, getAtlasResolutionSuffix}
